### PR TITLE
Update gr-rds for compatibility with GNURadio 3.9.

### PR DESCRIPTION
**Pull request by elafargue**
Basic testing done on RDS receiver, works fine.

Step 1: python bindings and cmake configuration
Step 2: update examples for Gnuradio companion

### CODE REVIEW

**Comment by bastibl** [comment]
Thanks for the PR. I didn't have a close look at GR 3.9 yet, but it looks good :-)
I just wondered:
- Why do you put back the docs directory?
- The docs seem to be copied from gr-satellites, at least it mentions satellites at several places.
- Why was it necessary to change the flowgraphs? Unfortunately, there are no good diffs, but it looks like you did significant changes. Can you explain a bit what you did and why?

**Comment by elafargue** [comment]
Yes, this was a bit of a quick job, I'm afraid... I'm not super familiar with the GNURadio build system and did indeed copy some of the docs directory from gr-satellites, I'll try to find a way to remove that directory or at least reduce it to the strict minimum. Let me try that and push an update to this PR later.

I updated the flow graphs because some of the APIs in GR 3.9 have changed and the old blocks needed a slightly different configuration in their parameters in order to work, but the flowgraph itself is essentially functionally identical to the old one

**Comment by elafargue** [comment]
It looks like GR 3.9 really likes to have a `docs` directory, and that one is mostly generated by `gr_modtool`. I have updated the PR to reflect this and use `gr-rds` as the name of the project for the autogenerated files.

The updated flowgraph looks like this (again, mostly because some for the Gnuradio APIs have changed requiring updates to the FIR filter definitions):
Screen Shot 2021-04-13 at 2 47 30 PM

**Comment by bastibl** [comment]
great, thank you! I noticed some minor issues, but I'll merge and open an issue to track them.

**Pull request merged**
